---
logging:
  level: INFO
  loggers:
    com.example: DEBUG
    io.dropwizard.hibernate: DEBUG
database:
  driverClass: org.mariadb.jdbc.Driver
  user: ${DB_USER}
  password: ${DB_PASSWORD}
  url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
