services:
  server:
    image: openjdk:11
    container_name: todo-app
    working_dir: /app
    volumes:
      - ./target/todo-app-1.0-SNAPSHOT.jar:/app/server.jar
      - ./config.yml:/app/config.yml
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER : root
      DB_PASSWORD: root
      DB_NAME : todos
    command: ["java", "-DDB_HOST=${DB_HOST}", "-DDB_PORT=${DB_PORT}", "-DDB_USER=${DB_USER}", "-DDB_PASSWORD=${DB_PASSWORD}", "-DDB_NAME=${DB_NAME}", "-jar", "server.jar", "server", "config.yml"]
  db:
    image: mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: todos
    volumes:
      - mariadb_data:/var/lib/mysql:Z
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  mariadb_data:
    driver: local

